DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'CAPTACION_FISICA') THEN
    DELETE FROM "TOMA_FISICA"."CAPTACION_FISICA";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'EXISTENCIA_UBICACION') THEN
    DELETE FROM "TOMA_FISICA"."EXISTENCIA_UBICACION";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'PLANIFICACION_LINEA') THEN
    DELETE FROM "TOMA_FISICA"."PLANIFICACION_LINEA";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'PLANIFICACION') THEN
    DELETE FROM "TOMA_FISICA"."PLANIFICACION";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'MAESTRO_UPLOAD') THEN
    DELETE FROM "TOMA_FISICA"."MAESTRO_UPLOAD";
  END IF;

  -- IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'USUARIO_UBICACION') THEN
  --   DELETE FROM "TOMA_FISICA"."USUARIO_UBICACION";
  -- END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'BITACORA') THEN
    DELETE FROM "TOMA_FISICA"."BITACORA";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'ESTADO') THEN
    DELETE FROM "TOMA_FISICA"."ESTADO";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'CATEGORIA') THEN
    DELETE FROM "TOMA_FISICA"."CATEGORIA";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'ALMACEN') THEN
    DELETE FROM "TOMA_FISICA"."ALMACEN";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'UBICACION') THEN
    DELETE FROM "TOMA_FISICA"."UBICACION";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'ARTICULO') THEN
    DELETE FROM "TOMA_FISICA"."ARTICULO";
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'TOMA_FISICA' AND table_name = 'USUARIO') THEN
    DELETE FROM "TOMA_FISICA"."USUARIO";
  END IF;
END $$;

DROP TABLE IF EXISTS "TOMA_FISICA"."CAPTACION_FISICA";
DROP TABLE IF EXISTS "TOMA_FISICA"."PLANIFICACION_LINEA";
DROP TABLE IF EXISTS "TOMA_FISICA"."EXISTENCIA_UBICACION";
-- DROP TABLE IF EXISTS "TOMA_FISICA"."USUARIO_UBICACION";
DROP TABLE IF EXISTS "TOMA_FISICA"."BITACORA";
DROP TABLE IF EXISTS "TOMA_FISICA"."PLANIFICACION";
DROP TABLE IF EXISTS "TOMA_FISICA"."ARTICULO";
DROP TABLE IF EXISTS "TOMA_FISICA"."UBICACION";
DROP TABLE IF EXISTS "TOMA_FISICA"."ALMACEN";
DROP TABLE IF EXISTS "TOMA_FISICA"."MAESTRO_UPLOAD";
DROP TABLE IF EXISTS "TOMA_FISICA"."ESTADO";
DROP TABLE IF EXISTS "TOMA_FISICA"."CATEGORIA";
DROP TABLE IF EXISTS "TOMA_FISICA".USUARIO;
DROP SCHEMA IF EXISTS "TOMA_FISICA" CASCADE;

CREATE SCHEMA "TOMA_FISICA";

CREATE TABLE "TOMA_FISICA".USUARIO(
    ID_USUARIO SERIAL PRIMARY KEY,
    USUARIO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    SUPER_USUARIO VARCHAR(255) NOT NULL,
    NIVEL_1 VARCHAR(2) NOT NULL, -- GERENTE
    NIVEL_2 VARCHAR(2) NOT NULL, -- CONTABLE
    NIVEL_3 VARCHAR(2) NOT NULL, -- JEFE DE ALMACEN
    NIVEL_4 VARCHAR(2) NOT NULL, -- SUPERVISOR
    NIVEL_5 VARCHAR(2) NOT NULL, -- CAPTACION FISICA
    PAIS VARCHAR(50) NOT NULL
); 

CREATE TABLE "TOMA_FISICA"."BITACORA" (
    "ID_BITACORA" SERIAL PRIMARY KEY,
    "ID_USUARIO" VARCHAR(255) NOT NULL REFERENCES "TOMA_FISICA".usuario(usuario),
    "ACCION" VARCHAR(255) NOT NULL,
    "TABLA" VARCHAR(50) NOT NULL,
    "FECHA_REGISTRO" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DETALLES" TEXT
);

-- con PAIS ----
CREATE TABLE "TOMA_FISICA"."UBICACION" (
    "UBICACION" VARCHAR(50) PRIMARY KEY,
    "DESCRIPCION" VARCHAR(254) NOT NULL,
    "PAIS" VARCHAR(50) NOT NULL
);

CREATE TABLE "TOMA_FISICA"."ALMACEN" (
    "ALMACEN" VARCHAR(50) PRIMARY KEY,
    "DESCRIPCION" VARCHAR(254) NOT NULL,
    "PAIS" VARCHAR(50) NOT NULL
);

CREATE TABLE "TOMA_FISICA"."MAESTRO_UPLOAD" (
    "MAESTRO" VARCHAR(20) NOT NULL,
    "ULTIMA_SUBIDA" TIMESTAMP NOT NULL,
    "PAIS" VARCHAR(50) NOT NULL
);

------ Sin PAIS -----
CREATE TABLE "TOMA_FISICA"."CATEGORIA" (
    "CATEGORIA" VARCHAR(50) PRIMARY KEY,
    "DESCRIPCION" VARCHAR(254) NOT NULL,
    "AGRUPACION" VARCHAR(12) NOT NULL
);

CREATE TABLE "TOMA_FISICA"."ESTADO" (
    "ESTADO" VARCHAR(50) PRIMARY KEY,
    "DESCRIPCION" VARCHAR(254) NOT NULL
);

CREATE TABLE "TOMA_FISICA"."ARTICULO" (
    "ARTICULO" VARCHAR(20) PRIMARY KEY,
    "DESCRIPCION" VARCHAR(254),
    "CATEGORIA_1" VARCHAR(50),
    "CATEGORIA_2" VARCHAR(50),
    FOREIGN KEY ("CATEGORIA_1") REFERENCES "TOMA_FISICA"."CATEGORIA" ("CATEGORIA"),
    FOREIGN KEY ("CATEGORIA_2") REFERENCES "TOMA_FISICA"."CATEGORIA" ("CATEGORIA")
);

-- CREATE TABLE "TOMA_FISICA"."USUARIO_UBICACION"(
--     "ID_USUARIO_UBICACION" SERIAL PRIMARY KEY,
--     "USUARIO" VARCHAR(255) NOT NULL,
--     "ID_UBICACION" VARCHAR(50) NOT NULL, 
--     FOREIGN KEY ("USUARIO") REFERENCES "TOMA_FISICA".USUARIO (USUARIO),
--     FOREIGN KEY ("ID_UBICACION") REFERENCES "TOMA_FISICA"."UBICACION" ("UBICACION")
-- );

CREATE TABLE "TOMA_FISICA"."PLANIFICACION" (
    "ID" SERIAL PRIMARY KEY, 
    "ESTADO" VARCHAR(50) NOT NULL,
    "FECHA" TIMESTAMP NOT NULL,
    "REPORTE_ESTADO" VARCHAR(50),
    "USUARIO" VARCHAR(50)
);

CREATE TABLE "TOMA_FISICA"."PLANIFICACION_LINEA" (
    "ID" SERIAL PRIMARY KEY,
    "PLANIFICACION_ID" INTEGER NOT NULL,
    "NOMBRE_TABLA_FILTRO" VARCHAR(50) NOT NULL,
    "VALOR_FILTRO" VARCHAR(50) NOT NULL,
    FOREIGN KEY ("PLANIFICACION_ID") REFERENCES "TOMA_FISICA"."PLANIFICACION" ("ID")
);

SELECT * FROM "TOMA_FISICA"."CAPTACION_FISICA" WHERE "ID_PLANIFICACION" = 25;

CREATE TABLE "TOMA_FISICA"."CAPTACION_FISICA" (
    "ID" SERIAL PRIMARY KEY,
    "ID_PLANIFICACION" INTEGER NOT NULL,
    "ARTICULO" VARCHAR(20),
    "DESCRIPCION" VARCHAR(254),
    "UBICACION" VARCHAR(50),
    "ALMACEN" VARCHAR(50),
    "LOTE" VARCHAR(50),
    "FECHA_EXPIRACION" TIMESTAMP NULL,
    "ETIQUETA" VARCHAR(50), -- "NUEVO" VARCHAR(50)
    "FECHA" TIMESTAMP NULL,
    "CANTIDAD" DECIMAL,
    "USUARIO" VARCHAR(50),
    "IMAGEN" BYTEA,
    "ESTADO" VARCHAR(50), 
    "SERIE" VARCHAR(100),
    "MODELO" VARCHAR(100),
    "OBSERVACION" VARCHAR(50),
    FOREIGN KEY ("ARTICULO") REFERENCES "TOMA_FISICA"."ARTICULO" ("ARTICULO"),
    FOREIGN KEY ("UBICACION") REFERENCES "TOMA_FISICA"."UBICACION" ("UBICACION"),
    FOREIGN KEY ("ALMACEN") REFERENCES "TOMA_FISICA"."ALMACEN" ("ALMACEN"),
    FOREIGN KEY ("ID_PLANIFICACION") REFERENCES "TOMA_FISICA"."PLANIFICACION" ("ID")
);

CREATE TABLE "TOMA_FISICA"."EXISTENCIA_UBICACION" (
    "ID" SERIAL PRIMARY KEY, 
    "ARTICULO" VARCHAR(20),
    "ID_PLANIFICACION" INTEGER NOT NULL,
    "UBICACION" VARCHAR(50),
    "ALMACEN" VARCHAR(50), 
    "LOTE" VARCHAR(50),
    "FECHA_EXPIRACION" TIMESTAMP NULL,
    "CANTIDAD" DECIMAL,
    "COSTO" DECIMAL,
    FOREIGN KEY ("ARTICULO") REFERENCES "TOMA_FISICA"."ARTICULO" ("ARTICULO"),
    FOREIGN KEY ("UBICACION") REFERENCES "TOMA_FISICA"."UBICACION" ("UBICACION"),
    FOREIGN KEY ("ALMACEN") REFERENCES "TOMA_FISICA"."ALMACEN" ("ALMACEN"),
    FOREIGN KEY ("ID_PLANIFICACION") REFERENCES "TOMA_FISICA"."PLANIFICACION" ("ID")
);

-- Columna para agregar en la nueva versión
ALTER TABLE "TOMA_FISICA"."PLANIFICACION" ADD COLUMN "NOMBRE" VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE "TOMA_FISICA"."CAPTACION_FISICA"
  ADD COLUMN IF NOT EXISTS "SERIE" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "MODELO" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "OBSERVACION" VARCHAR(50);
