BEGIN;

ALTER TABLE "TOMA_FISICA"."PLANIFICACION"
    ADD COLUMN IF NOT EXISTS "OBSERVACION_CIERRE" TEXT;

ALTER TABLE "TOMA_FISICA"."PLANIFICACION"
    ADD COLUMN IF NOT EXISTS "USUARIO_APROBACION" VARCHAR(100);

ALTER TABLE "TOMA_FISICA"."PLANIFICACION"
    ADD COLUMN IF NOT EXISTS "FECHA_APROBACION" TIMESTAMP;

COMMENT ON COLUMN "TOMA_FISICA"."PLANIFICACION"."OBSERVACION_CIERRE" IS 'Comentario registrado durante la aprobación del cierre de inventario.';
COMMENT ON COLUMN "TOMA_FISICA"."PLANIFICACION"."USUARIO_APROBACION" IS 'Usuario responsable que firmó digitalmente la aprobación.';
COMMENT ON COLUMN "TOMA_FISICA"."PLANIFICACION"."FECHA_APROBACION" IS 'Fecha y hora en la que se confirmó la aprobación del reporte.';

COMMIT;
